#!/usr/bin/env python3
"""Shrink the animated-logo component before it ships.

    python3 tools/optimize-logo-sting.py

Reads  assets/_src/logo-sting-original.js   (the design export, never published)
Writes assets/js/logo-sting.js              (what the site actually loads)

The component draws the logo as eleven separate strokes, each one an inlined PNG
used as a CSS mask. Only the alpha channel of those PNGs does anything — the
colour comes from the `tint` attribute — but the export carries full RGBA
artwork, so roughly half the file is colour data that is thrown away at render
time. Copying alpha into the colour channels makes them uniform, which PNG
compresses to almost nothing, and leaves the mask bit-for-bit identical.

That alone halves it, so there is no need to touch the resolution: the strokes
stay sharp at any size the page asks for. (Downscaling them is a false economy
anyway — resampling turns crisp edges into gradients that compress worse.)

Re-run this whenever a new logo-sting.js export lands in assets/_src/.

Needs Pillow:  pip install Pillow
"""

import base64
import gzip
import io
import os
import re
import sys

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow is not installed. Run: pip install Pillow")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "assets", "_src", "logo-sting-original.js")
DST = os.path.join(ROOT, "assets", "js", "logo-sting.js")

BANNER = """// Generated by tools/optimize-logo-sting.py — do not edit by hand.
// Source: assets/_src/logo-sting-original.js (the design export).
// The inlined stroke masks have had their colour channels replaced with their
// own alpha, which is what the CSS mask reads. Same pixels, about half the size.
"""

PATTERN = re.compile(r'("src":"data:image/png;base64,)([A-Za-z0-9+/=]+)')


def main():
    if not os.path.exists(SRC):
        sys.exit("missing " + os.path.relpath(SRC, ROOT))

    src = open(SRC, encoding="utf-8").read()
    count = 0

    def repl(m):
        nonlocal count
        count += 1
        im = Image.open(io.BytesIO(base64.b64decode(m.group(2)))).convert("RGBA")
        a = im.split()[-1]
        # Alpha in every channel: the mask is unchanged, and luminance now
        # matches it too, so a browser reading either one renders the same.
        flat = Image.merge("RGBA", (a, a, a, a))
        buf = io.BytesIO()
        flat.save(buf, "PNG", optimize=True)
        return m.group(1) + base64.b64encode(buf.getvalue()).decode()

    out = BANNER + PATTERN.sub(repl, src)

    os.makedirs(os.path.dirname(DST), exist_ok=True)
    with open(DST, "w", encoding="utf-8") as f:
        f.write(out)

    def sizes(text):
        raw = text.encode()
        return len(raw) / 1024, len(gzip.compress(raw, 9)) / 1024

    b_raw, b_gz = sizes(src)
    a_raw, a_gz = sizes(out)
    print(f"  {count} stroke masks rebuilt")
    print(f"  {b_raw:6.0f} KB -> {a_raw:6.0f} KB on disk")
    print(f"  {b_gz:6.0f} KB -> {a_gz:6.0f} KB gzipped (what visitors download)")
    print(f"\nWrote {os.path.relpath(DST, ROOT)}.")


if __name__ == "__main__":
    main()
